#!/bin/bash

echo -e "\e[32m=== === === === === === === === === === === === === === === === === === === \e[31;1;5m"
figlet -k "Fin de l'installation!!!"
echo -e "\e[0m\e[32m=== === === === === === === === === === === === === === === === === === === \e[0m"
echo ""
echo "Traitement ...."
