#!/bin/bash

sleep 5
clear
for ((i=1;i<=10;i++));do
	echo "Chargement en cours..."
	echo -n "("
	for ((j=i;j!=0;j--));do
		echo -n "°"
	done
	for ((l=10-i;l!=0;l--));do
		echo -n " "
	done
	echo ")"
	sleep 1
	if [ "$i" != "10" ];then
		clear
	fi
done
echo ""
echo -e "\e[34m================================================================================\e[31;5m"
figlet -k "Votre paquet est desinstaller"
echo -e "\e[0m\e[34m=============================================================================\e[0m"
